sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"

services:
  - postgresql
  - redis-server

before_install:
  - psql -c 'create database fswd_seed_test;' -U postgres

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm test
